"""
Registre des services disponibles.
Chaque service = dict avec métadonnées, dépendances, ports UFW, config_fields, etc.
"""

# ── Champs de configuration globaux (toujours affichés) ──
GLOBAL_CONFIG_FIELDS = [
    {
        "id": "ansible_host",
        "label": "Hôte cible (IP ou hostname)",
        "type": "text",
        "required": True,
        "placeholder": "206.0.110.38",
        "default": "",
    },
    {
        "id": "ansible_user",
        "label": "Utilisateur SSH",
        "type": "text",
        "required": True,
        "placeholder": "deploy",
        "default": "",
    },
    {
        "id": "project_name",
        "label": "Nom du projet",
        "type": "text",
        "required": False,
        "placeholder": "my-stack",
        "default": "my-stack",
    },
    {
        "id": "inventory_group",
        "label": "Groupe d'inventaire Ansible",
        "type": "text",
        "required": False,
        "placeholder": "my_vps",
        "default": "my_vps",
        "help": "Nom logique du groupe dans le fichier inventory.ini (ex: [my_vps]). Sert uniquement à organiser vos serveurs dans Ansible (production, staging…). Ce n'est PAS un utilisateur SSH — c'est juste une étiquette interne.",
    },
    {
        "id": "base_domain",
        "label": "Domaine de base",
        "type": "text",
        "required": False,
        "placeholder": "example.com",
        "default": "example.com",
    },
    {
        "id": "admin_email",
        "label": "Email (Let's Encrypt)",
        "type": "email",
        "required": False,
        "placeholder": "admin@example.com",
        "default": "",
    },
]

SERVICES = [
    # ── Système ──
    {
        "id": "ufw",
        "label": "UFW Firewall",
        "description": "Firewall simplifié — politique deny-all + ouverture sélective",
        "category": "system",
        "requires": [],
        "default_enabled": False,
        "locked": True,
        "ufw_ports": [],
        "is_docker": False,
        "has_version": False,
        "config_fields": [],
    },
    {
        "id": "ssh_hardening",
        "label": "SSH Hardening",
        "description": "Clé only, ciphers modernes, root interdit, rate-limit",
        "category": "system",
        "requires": [],
        "default_enabled": False,
        "locked": True,
        "ufw_ports": [],
        "is_docker": False,
        "has_version": False,
        "config_fields": [
            {
                "id": "ssh_port",
                "label": "Port SSH",
                "type": "number",
                "required": False,
                "default": 22,
                "min": 1,
                "max": 65535,
            },
            {
                "id": "ssh_max_auth_tries",
                "label": "SSH MaxAuthTries",
                "type": "number",
                "required": False,
                "default": 3,
                "min": 1,
                "max": 10,
            },
        ],
    },
    {
        "id": "unattended_upgrades",
        "label": "Mises à jour auto",
        "description": "Patches de sécurité appliqués automatiquement chaque jour",
        "category": "system",
        "requires": [],
        "default_enabled": False,
        "locked": True,
        "ufw_ports": [],
        "is_docker": False,
        "has_version": False,
        "config_fields": [],
    },
    # ── Infra ──
    {
        "id": "docker",
        "label": "Docker Engine",
        "description": "Runtime de containers — requis par tous les services Docker",
        "category": "infra",
        "requires": [],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": False,
        "has_version": False,
        "config_fields": [
            {
                "id": "stack_dir",
                "label": "Répertoire stack",
                "type": "select",
                "required": False,
                "default": "/opt/stack",
                "options": ["/opt/stack", "/srv/stack", "/home/deploy/stack"],
                "help": "Répertoire sur le serveur où seront stockés les fichiers Docker Compose et les données.",
            },
            {
                "id": "docker_network",
                "label": "Réseau Docker",
                "type": "select",
                "required": False,
                "default": "web",
                "options": ["web", "proxy", "frontend", "traefik"],
                "help": "Nom du réseau Docker partagé entre Traefik et les services exposés.",
            },
        ],
    },
    {
        "id": "netbird",
        "label": "NetBird VPN",
        "description": "VPN mesh sécurisé — accès privé au serveur",
        "category": "infra",
        "requires": [],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [{"port": "51820", "proto": "udp"}],
        "is_docker": False,
        "has_version": False,
        "config_fields": [
            {
                "id": "netbird_setup_key",
                "label": "Clé de setup NetBird",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "Depuis https://app.netbird.io/",
            },
            {
                "id": "restrict_ssh_to_vpn",
                "label": "Restreindre SSH au VPN uniquement",
                "type": "checkbox",
                "required": False,
                "default": False,
            },
            {
                "id": "netbird_vpn_network",
                "label": "Réseau VPN NetBird",
                "type": "select",
                "required": False,
                "default": "100.64.0.0/10",
                "options": ["100.64.0.0/10", "100.64.0.0/16", "10.0.0.0/8", "172.16.0.0/12"],
                "help": "Plage réseau utilisée par NetBird. 100.64.0.0/10 est la valeur par défaut de NetBird (CGNAT).",
            },
        ],
    },
    # ── Reverse Proxy ──
    {
        "id": "traefik",
        "label": "Traefik",
        "description": "Reverse proxy avec découverte auto Docker + Let's Encrypt",
        "category": "reverse_proxy",
        "requires": ["docker"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [{"port": "80", "proto": "tcp"}, {"port": "443", "proto": "tcp"}],
        "is_docker": True,
        "has_version": True,
        "config_fields": [
            {
                "id": "enable_https",
                "label": "Activer HTTPS (Let's Encrypt)",
                "type": "checkbox",
                "required": False,
                "default": False,
            },
        ],
    },
    # ── Sécurité ──
    {
        "id": "crowdsec",
        "label": "CrowdSec (Docker)",
        "description": "Détection d'intrusions — analyse les logs, crée des décisions de ban",
        "category": "security",
        "requires": ["docker"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "warning_if_disabled": "⚠️ Sans CrowdSec, aucune détection d'intrusion ne protégera votre serveur.",
        "config_fields": [
            {
                "id": "crowdsec_lapi_key",
                "label": "Clé LAPI CrowdSec",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "openssl rand -hex 16",
            },
        ],
    },
    {
        "id": "crowdsec_bouncer",
        "label": "CrowdSec Bouncer (hôte)",
        "description": "Bloque les IPs malveillantes via nftables au niveau kernel",
        "category": "security",
        "requires": ["crowdsec"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": False,
        "has_version": False,
        "warning_if_disabled": "⚠️ Sans le bouncer, CrowdSec détecte mais ne bloque rien !",
        "config_fields": [
            {
                "id": "bouncer_update_frequency",
                "label": "Fréquence de mise à jour",
                "type": "select",
                "required": False,
                "default": "10s",
                "options": ["5s", "10s", "30s", "1m", "5m"],
                "help": "Fréquence à laquelle le bouncer interroge la LAPI pour les nouvelles décisions.",
            },
            {
                "id": "bouncer_deny_action",
                "label": "Action de blocage",
                "type": "select",
                "required": False,
                "default": "DROP",
                "options": ["DROP", "REJECT", "TARPIT"],
                "help": "DROP silencieux (recommandé), REJECT envoie un refus, TARPIT ralentit l'attaquant.",
            },
            {
                "id": "bouncer_log_level",
                "label": "Niveau de log",
                "type": "select",
                "required": False,
                "default": "info",
                "options": ["trace", "debug", "info", "warning", "error"],
                "help": "Verbosité des logs du bouncer. 'info' est recommandé en production.",
            },
        ],
    },
    # ── Monitoring ──
    {
        "id": "grafana",
        "label": "Grafana",
        "description": "Dashboards de visualisation — métriques système et sécurité",
        "category": "monitoring",
        "requires": ["docker", "prometheus"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "config_fields": [
            {
                "id": "grafana_admin_password",
                "label": "Mot de passe admin Grafana",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "Mot de passe fort",
            },
            {
                "id": "grafana_subdomain",
                "label": "Sous-domaine Grafana",
                "type": "text",
                "required": False,
                "default": "dashboard",
                "placeholder": "dashboard",
            },
        ],
    },
    {
        "id": "prometheus",
        "label": "Prometheus",
        "description": "Collecte de métriques — scrape CrowdSec, Traefik, Node Exporter",
        "category": "monitoring",
        "requires": ["docker"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "config_fields": [
            {
                "id": "prometheus_retention",
                "label": "Durée de rétention",
                "type": "select",
                "required": False,
                "default": "30d",
                "options": ["7d", "14d", "30d", "60d", "90d", "180d", "365d"],
                "help": "Durée pendant laquelle Prometheus conserve les métriques.",
            },
            {
                "id": "prometheus_retention_size",
                "label": "Taille max de rétention",
                "type": "select",
                "required": False,
                "default": "1GB",
                "options": ["512MB", "1GB", "2GB", "5GB", "10GB", "20GB"],
                "help": "Espace disque max alloué aux métriques Prometheus.",
            },
            {
                "id": "prometheus_scrape_interval",
                "label": "Intervalle de scrape",
                "type": "select",
                "required": False,
                "default": "15s",
                "options": ["5s", "10s", "15s", "30s", "1m", "2m"],
                "help": "Fréquence de collecte des métriques. 15s est un bon compromis.",
            },
        ],
    },
    {
        "id": "node_exporter",
        "label": "Node Exporter",
        "description": "Métriques système de l'hôte (CPU, RAM, disque, réseau)",
        "category": "monitoring",
        "requires": ["docker", "prometheus"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "config_fields": [],
    },
    # ── Apps ──
    {
        "id": "vaultwarden",
        "label": "Vaultwarden",
        "description": "Gestionnaire de mots de passe compatible Bitwarden",
        "category": "apps",
        "requires": ["docker", "traefik"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "subdomain_var": "vaultwarden_subdomain",
        "default_subdomain": "vault",
        "config_fields": [
            {
                "id": "vaultwarden_subdomain",
                "label": "Sous-domaine Vaultwarden",
                "type": "text",
                "required": False,
                "default": "vault",
                "placeholder": "vault",
            },
            {
                "id": "vaultwarden_signups_allowed",
                "label": "Autoriser les inscriptions",
                "type": "checkbox",
                "required": False,
                "default": False,
            },
        ],
    },
    {
        "id": "uptime_kuma",
        "label": "Uptime Kuma",
        "description": "Monitoring d'uptime — surveille vos services et alerte",
        "category": "apps",
        "requires": ["docker", "traefik"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "subdomain_var": "uptime_kuma_subdomain",
        "default_subdomain": "status",
        "config_fields": [
            {
                "id": "uptime_kuma_subdomain",
                "label": "Sous-domaine Uptime Kuma",
                "type": "text",
                "required": False,
                "default": "status",
                "placeholder": "status",
            },
        ],
    },
    {
        "id": "portainer",
        "label": "Portainer",
        "description": "Interface web de gestion Docker",
        "category": "apps",
        "requires": ["docker", "traefik"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "subdomain_var": "portainer_subdomain",
        "default_subdomain": "portainer",
        "config_fields": [
            {
                "id": "portainer_subdomain",
                "label": "Sous-domaine Portainer",
                "type": "text",
                "required": False,
                "default": "portainer",
                "placeholder": "portainer",
            },
        ],
    },
    {
        "id": "bentopdf",
        "label": "BentoPDF",
        "description": "Convertisseur PDF en ligne",
        "category": "apps",
        "requires": ["docker", "traefik"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": False,
        "subdomain_var": "bentopdf_subdomain",
        "default_subdomain": "pdf",
        "config_fields": [
            {
                "id": "bentopdf_subdomain",
                "label": "Sous-domaine BentoPDF",
                "type": "text",
                "required": False,
                "default": "pdf",
                "placeholder": "pdf",
            },
        ],
    },
    {
        "id": "git",
        "label": "Git",
        "description": "Utilitaire Git — git clone, pull, push, etc.",
        "category": "system",
        "requires": [],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": False,
        "has_version": False,
        "config_fields": [
            {
                "id": "git_user_name",
                "label": "Git user.name",
                "type": "text",
                "required": False,
                "default": "",
                "placeholder": "John Doe",
            },
            {
                "id": "git_user_email",
                "label": "Git user.email",
                "type": "text",
                "required": False,
                "default": "",
                "placeholder": "john@example.com",
            },
        ],
    },
    {
        "id": "nextcloud",
        "label": "Nextcloud",
        "description": "Cloud privé — fichiers, agenda, contacts, collaboration",
        "category": "apps",
        "requires": ["docker", "traefik"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "subdomain_var": "nextcloud_subdomain",
        "default_subdomain": "cloud",
        "config_fields": [
            {
                "id": "nextcloud_subdomain",
                "label": "Sous-domaine Nextcloud",
                "type": "text",
                "required": False,
                "default": "cloud",
                "placeholder": "cloud",
            },
            {
                "id": "nextcloud_admin_user",
                "label": "Utilisateur admin Nextcloud",
                "type": "text",
                "required": True,
                "default": "admin",
                "placeholder": "admin",
            },
            {
                "id": "nextcloud_admin_password",
                "label": "Mot de passe admin Nextcloud",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "Mot de passe fort",
            },
            {
                "id": "nextcloud_db_password",
                "label": "Mot de passe DB Nextcloud (user)",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "openssl rand -hex 16",
            },
            {
                "id": "nextcloud_db_root_password",
                "label": "Mot de passe root MariaDB",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "openssl rand -hex 16 (différent du précédent)",
            },
        ],
    },
    {
        "id": "n8n",
        "label": "n8n",
        "description": "Automatisation de workflows — alternative open-source à Zapier",
        "category": "apps",
        "requires": ["docker", "traefik"],
        "default_enabled": False,
        "locked": False,
        "ufw_ports": [],
        "is_docker": True,
        "has_version": True,
        "subdomain_var": "n8n_subdomain",
        "default_subdomain": "n8n",
        "config_fields": [
            {
                "id": "n8n_subdomain",
                "label": "Sous-domaine n8n",
                "type": "text",
                "required": False,
                "default": "n8n",
                "placeholder": "n8n",
            },
            {
                "id": "n8n_basic_auth_user",
                "label": "Utilisateur auth n8n",
                "type": "text",
                "required": False,
                "default": "admin",
                "placeholder": "admin",
            },
            {
                "id": "n8n_basic_auth_password",
                "label": "Mot de passe auth n8n",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "Mot de passe fort",
            },
        ],
    },
    # ── DNS & Ad-blocking ──
    {
        "id": "pihole",
        "label": "Pi-hole",
        "description": "Serveur DNS avec blocage de publicités et trackers",
        "category": "dns",
        "requires": ["docker"],
        "default_enabled": False,
        "locked": False,
        "conflicts_with": ["adguard_home"],
        "ufw_ports": [{"port": "53", "proto": "tcp"}, {"port": "53", "proto": "udp"}],
        "is_docker": True,
        "has_version": True,
        "subdomain_var": "pihole_subdomain",
        "default_subdomain": "pihole",
        "config_fields": [
            {
                "id": "pihole_subdomain",
                "label": "Sous-domaine Pi-hole",
                "type": "text",
                "required": False,
                "default": "pihole",
                "placeholder": "pihole",
            },
            {
                "id": "pihole_web_password",
                "label": "Mot de passe admin Pi-hole",
                "type": "password",
                "required": True,
                "default": "",
                "placeholder": "Mot de passe fort",
            },
            {
                "id": "pihole_dns_port",
                "label": "Port DNS Pi-hole",
                "type": "number",
                "required": False,
                "default": 53,
                "min": 1,
                "max": 65535,
                "placeholder": "53",
            },
        ],
    },
    {
        "id": "adguard_home",
        "label": "AdGuard Home",
        "description": "Serveur DNS avec blocage de publicités — alternative à Pi-hole",
        "category": "dns",
        "requires": ["docker"],
        "default_enabled": False,
        "locked": False,
        "conflicts_with": ["pihole"],
        "ufw_ports": [{"port": "53", "proto": "tcp"}, {"port": "53", "proto": "udp"}],
        "is_docker": True,
        "has_version": True,
        "subdomain_var": "adguard_subdomain",
        "default_subdomain": "adguard",
        "config_fields": [
            {
                "id": "adguard_subdomain",
                "label": "Sous-domaine AdGuard Home",
                "type": "text",
                "required": False,
                "default": "adguard",
                "placeholder": "adguard",
            },
            {
                "id": "adguard_dns_port",
                "label": "Port DNS AdGuard",
                "type": "number",
                "required": False,
                "default": 53,
                "min": 1,
                "max": 65535,
                "placeholder": "53",
            },
        ],
    },
]

CATEGORIES = {
    "system": {"label": "Système", "icon": "🖥️", "order": 0},
    "infra": {"label": "Infrastructure", "icon": "🏗️", "order": 1},
    "reverse_proxy": {"label": "Reverse Proxy", "icon": "🔀", "order": 2},
    "security": {"label": "Sécurité", "icon": "🛡️", "order": 3},
    "monitoring": {"label": "Monitoring", "icon": "📊", "order": 4},
    "dns": {"label": "DNS & Ad-blocking", "icon": "🌐", "order": 5},
    "apps": {"label": "Applications", "icon": "📦", "order": 6},
}


def get_service_by_id(service_id: str) -> dict | None:
    for s in SERVICES:
        if s["id"] == service_id:
            return s
    return None


def get_services_by_category() -> dict:
    result = {}
    for cat_id, cat_meta in sorted(CATEGORIES.items(), key=lambda x: x[1]["order"]):
        result[cat_id] = {
            **cat_meta,
            "services": [s for s in SERVICES if s["category"] == cat_id],
        }
    return result
